on:
  workflow_dispatch:

name: Build ubuntu package as artifact

env:
  swift_package_resolve: swift package resolve
  swift_build: swift build -c release -Xswiftc -g -Xswiftc -static-stdlib
  swift_test: swift test
  cache_version: 1

jobs:
  linux:
    runs-on: ubuntu-22.04
    container: swift:6.1.0-jammy
    name: Linux
    steps:
    - name: Get Swift Version
      id: get-swift-version
      run: echo "version=$(swift -version | head -n 1 | sed s/,// )" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/checkout@v4
    - name: Copy Swift Backtrace
      run: cp /usr/libexec/swift/linux/swift-backtrace-static ./swift-backtrace
    - name: Cache resolved dependencies
      id: cache-resolved-dependencies
      uses: actions/cache@v4
      with:
        path: |
          .build
          Package.resolved
        key: ${{ runner.os }}-${{ steps.get-swift-version.outputs.version }}-${{ env.cache_version }}-spm-deps-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.get-swift-version.outputs.version }}-${{ env.cache_version }}-spm-deps-
    - name: Resolve dependencies
      if: steps.cache-resolved-dependencies.outputs.cache-hit != 'true'
      run: ${{ env.swift_package_resolve }}
    - name: Build
      run: |
        ${{ env.swift_build }}
        mv .build/release/Run geocoding-api
    - name: Package
      uses: gravitl/github-action-fpm@master
      with:
        fpm_args: './build'
        fpm_opts: '-s dir -t deb -n geocoding-api -v ${{github.ref_name}} --deb-user geoocoding-api --deb-group geoocoding-api --deb-systemd build/geocoding-api.service --deb-default build/geocoding-api.env --before-install build/geocoding-before-install.sh --before-upgrade build/geocoding-before-install.sh geocoding-api=/usr/local/bin/'
    - name: Rename deb file
      run: mv geocoding-api_${{github.ref_name}}_amd64.deb geocoding-api_${{github.ref_name}}_jammy_amd64.deb
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        artifacts: 'geocoding-api_${{github.ref_name}}_jammy_amd64.deb'
        draft: true